name: Package DocFX Template

on:
  push:
    paths:
      - 'docs/docfx/templates/material/**'
      - '!docs/docfx/templates/material.zip'
  workflow_dispatch:

concurrency:
  group: publish-docs
  cancel-in-progress: false

jobs:
  package_and_commit:
    runs-on: ubuntu-latest
    env:
      ZIP_DIR: docs/docfx/templates/material
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true
          token: ${{ secrets.RISINGV_DOCS_PAT }}
          fetch-depth: 0

      - name: Package template
        run: |
          ZIP_PATH="${ZIP_DIR}.zip"
          rm -rf "$ZIP_PATH"
          zip -r "$ZIP_PATH" "$ZIP_DIR"

      - name: Commit package file if it changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          ZIP_PATH="${ZIP_DIR}.zip"

          if git diff --quiet --exit-code "$ZIP_PATH"; then
            echo "No changes in $ZIP_PATH; skipping commit."
            exit 0
          fi

          git add "$ZIP_PATH"
          git commit -m "Auto-update template: ${ZIP_DIR##*/}.zip"
          git push